### ISSUE TITLE
Make well, but Make Check failed.

### ISSUE THREAD

**Issue by MaoJianwei** [p4lang/PI#228]
Steps:

git clone https://github.com/p4lang/PI.git
git submodule update --init --recursive
./autogen.sh
./configure --with-bmv2 --with-proto
sudo make
sudo make check

and....
This is the log, thank you!

```

======================================
   PI 0.1: tests/CLI/test-suite.log
======================================

# TOTAL: 13
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  13
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: table_dump
================

Traceback (most recent call last):
  File "./run_one_test.py", line 219, in <module>
    main()
  File "./run_one_test.py", line 134, in main
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
FAIL table_dump.test (exit status: 1)

FAIL: table_dump_valid
======================

Traceback (most recent call last):
  File "./run_one_test.py", line 219, in <module>
    main()
  File "./run_one_test.py", line 134, in main
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
FAIL table_dump_valid.test (exit status: 1)

FAIL: table_indirect
====================

Traceback (most recent call last):
  File "./run_one_test.py", line 219, in <module>
    main()
  File "./run_one_test.py", line 134, in main
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
FAIL table_indirect.test (exit status: 1)

FAIL: table_wkey
================

Traceback (most recent call last):
  File "./run_one_test.py", line 219, in <module>
    main()
  File "./run_one_test.py", line 134, in main
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
FAIL table_wkey.test (exit status: 1)

FAIL: device_commands
=====================

Traceback (most recent call last):
  File "./run_one_test.py", line 219, in <module>
    main()
  File "./run_one_test.py", line 134, in main
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
FAIL device_commands.test (exit status: 1)

FAIL: counter
=============

Traceback (most recent call last):
  File "./run_one_test.py", line 219, in <module>
    main()
  File "./run_one_test.py", line 134, in main
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
FAIL counter.test (exit status: 1)

FAIL: counter_direct
====================

Traceback (most recent call last):
  File "./run_one_test.py", line 219, in <module>
    main()
  File "./run_one_test.py", line 134, in main
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
FAIL counter_direct.test (exit status: 1)

FAIL: meter
===========

Traceback (most recent call last):
  File "./run_one_test.py", line 219, in <module>
    main()
  File "./run_one_test.py", line 134, in main
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
FAIL meter.test (exit status: 1)

FAIL: meter_direct
==================

Traceback (most recent call last):
  File "./run_one_test.py", line 219, in <module>
    main()
  File "./run_one_test.py", line 134, in main
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
FAIL meter_direct.test (exit status: 1)

FAIL: counter_and_meter_direct
==============================

Traceback (most recent call last):
  File "./run_one_test.py", line 219, in <module>
    main()
  File "./run_one_test.py", line 134, in main
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
FAIL counter_and_meter_direct.test (exit status: 1)

FAIL: direct_res_reset
======================

Traceback (most recent call last):
  File "./run_one_test.py", line 219, in <module>
    main()
  File "./run_one_test.py", line 134, in main
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
FAIL direct_res_reset.test (exit status: 1)

FAIL: device_update
===================

Traceback (most recent call last):
  File "./run_one_test.py", line 219, in <module>
    main()
  File "./run_one_test.py", line 134, in main
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
FAIL device_update.test (exit status: 1)

FAIL: act_prof
==============

Traceback (most recent call last):
  File "./run_one_test.py", line 219, in <module>
    main()
  File "./run_one_test.py", line 134, in main
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
FAIL act_prof.test (exit status: 1)


```

**Comment by antoninbas** [comment]
Maybe you don't have `libtool` installed on your machine? Could you check and install it if it's needed?

**Comment by MaoJianwei** [comment]
apt shows that：

libtool is already the newest version (2.4.6-0.1)

**Comment by antoninbas** [comment]
you need `libtool-bin` as well I believe
Did you actually try running libtool to make sure that the binary was available?

**Comment by MaoJianwei** [comment]
problem solved, please review and merge https://github.com/p4lang/PI/pull/229 , thank you!

**Comment by MaoJianwei** [comment]
I amended the commit, could you please review again, thank you!

https://github.com/p4lang/PI/pull/229
